### ISSUE TITLE
Mastodon Client

### ISSUE THREAD

**Issue by marcschuler** [Clement87/Pepito-API#2]
Hi,

I wrote a mastodon bot for Pépito. 
The account is [@PepitoTheCat@mastodon.social](https://mastodon.social/@PepitoTheCat) and the source code is available at https://github.com/marcschuler/pepito-mastodon

It ~~is a mess without unit tests~~ already works and the first post [is up](https://mastodon.social/@PepitoTheCat/113103840117176222).

**Comment by clement87** [comment]
Hi, there is only one post, it doesn't seem to update.

**Comment by clement87** [comment]
It seems to work now, I added the link, thank you

**Comment by marcschuler** [comment]
Yeah, I had a problem with reconnecting to the server. I think it's fixed but I'm monitoring it over the next few days
