### ISSUE TITLE
Pépito C++ program

### ISSUE THREAD

**Issue by Avicted** [Clement87/Pepito-API#8]
Hello!

I have created a C++ program that connects to the API and parses every message.
The program starts with testing the parsing method with local test data.

I think the project could be a good "base"  to extend upon.

[https://github.com/Avicted/pepito_app](https://github.com/Avicted/pepito_app)

Best regards,
Victor

**Comment by clement87** [comment]
Hi,
thanks for sharing,
so it's more like an implementation example than a library ?   
Maybe I could add a the link in the example section.

**Comment by Avicted** [comment]
Hi!

Exactly! It's a showcase of how one could create a native application that reacts to the events.

I agree that it would fit into the example section.

Best regards,
Victor
